export const BUILDINGS_DATA = {
    fountain: {
        name: "Çeşme",
        type: "producer",
        baseCost: { karma: 12 },
        costMultiplier: 1.15,
        production: 0.4,
        outputResource: "karma",
        capacityPerUnit: 0,
        consumes: null,
        unlock: { type: "resource", id: "karma", amount: 10 },
    },
    mansion: {
        name: "Konak",
        type: "bonus",
        baseCost: { karma: 40, su: 15 },
        costMultiplier: 1.24,
        targetResource: "karma",
        bonusPerLevel: 0.15,
        unlock: { type: "building", id: "fountain", count: 1 },
    },
    well: {
        name: "Kuyu",
        type: "producer",
        baseCost: { karma: 36 },
        costMultiplier: 1.15,
        production: 0.7,
        outputResource: "su",
        capacityPerUnit: 420,
        consumes: null,
        unlock: { type: "building", id: "fountain", count: 5 },
    },
    aqueduct: {
        name: "Su Kemeri",
        type: "bonus",
        baseCost: { karma: 115, su: 25 },
        costMultiplier: 1.24,
        targetResource: "su",
        bonusPerLevel: 0.15,
        unlock: { type: "building", id: "well", count: 1 },
    },
    farm: {
        name: "Tarla",
        type: "producer",
        baseCost: { karma: 110, su: 45 },
        costMultiplier: 1.15,
        production: 1.3,
        outputResource: "yiyecek",
        capacityPerUnit: 780,
        consumes: null,
        unlock: { type: "building", id: "well", count: 5 },
    },
    mill: {
        name: "Değirmen",
        type: "bonus",
        baseCost: { karma: 350, su: 105, yiyecek: 55 },
        costMultiplier: 1.24,
        targetResource: "yiyecek",
        bonusPerLevel: 0.15,
        unlock: { type: "building", id: "farm", count: 1 },
    },
    lumberjack: {
        name: "Oduncu",
        type: "producer",
        baseCost: { karma: 325, yiyecek: 130 },
        costMultiplier: 1.15,
        production: 2.3,
        outputResource: "odun",
        capacityPerUnit: 1400,
        consumes: null,
        unlock: { type: "building", id: "farm", count: 5 },
    },
    lumbermill: {
        name: "Keresteci",
        type: "bonus",
        baseCost: { karma: 1040, yiyecek: 310, odun: 155 },
        costMultiplier: 1.24,
        targetResource: "odun",
        bonusPerLevel: 0.15,
        unlock: { type: "building", id: "lumberjack", count: 1 },
    },
    mine: {
        name: "Maden",
        type: "producer",
        baseCost: { karma: 975, odun: 390 },
        costMultiplier: 1.15,
        production: 4.2,
        outputResource: "maden",
        capacityPerUnit: 2500,
        consumes: null,
        unlock: { type: "building", id: "lumberjack", count: 5 },
    },
    blacksmith: {
        name: "Demirci",
        type: "bonus",
        baseCost: { karma: 3120, odun: 940, maden: 470 },
        costMultiplier: 1.24,
        targetResource: "maden",
        bonusPerLevel: 0.15,
        unlock: { type: "building", id: "mine", count: 1 },
    },
    academy: {
        name: "Akademi",
        type: "producer",
        baseCost: { karma: 2900, maden: 1160 },
        costMultiplier: 1.15,
        production: 7.5,
        outputResource: "bilgi",
        capacityPerUnit: 4500,
        consumes: null,
        unlock: { type: "building", id: "mine", count: 5 },
    },
    library: {
        name: "Kütüphane",
        type: "bonus",
        baseCost: { karma: 9280, maden: 2800, bilgi: 1400 },
        costMultiplier: 1.24,
        targetResource: "bilgi",
        bonusPerLevel: 0.15,
        unlock: { type: "building", id: "academy", count: 1 },
    },
    temple: {
        name: "Tapınak",
        type: "producer",
        baseCost: { karma: 8750, bilgi: 3500 },
        costMultiplier: 1.15,
        production: 13.5,
        outputResource: "inanc",
        capacityPerUnit: 8100,
        consumes: null,
        unlock: { type: "building", id: "academy", count: 5 },
    },
    altar: {
        name: "Sunak",
        type: "bonus",
        baseCost: { karma: 28000, bilgi: 8400, inanc: 4200 },
        costMultiplier: 1.24,
        targetResource: "inanc",
        bonusPerLevel: 0.15,
        unlock: { type: "building", id: "temple", count: 1 },
    },
    garden: {
        name: "Bahçe",
        type: "producer",
        baseCost: { karma: 26000, inanc: 10400 },
        costMultiplier: 1.15,
        production: 24.5,
        outputResource: "baharat",
        capacityPerUnit: 14700,
        consumes: null,
        unlock: { type: "building", id: "temple", count: 5 },
    },
    spiceMill: {
        name: "Baharat Değirmeni",
        type: "bonus",
        baseCost: { karma: 83200, inanc: 25000, baharat: 12500 },
        costMultiplier: 1.24,
        targetResource: "baharat",
        bonusPerLevel: 0.15,
        unlock: { type: "building", id: "garden", count: 1 },
    },
    vineyard: {
        name: "Üzüm Bağı",
        type: "producer",
        baseCost: { karma: 79000, baharat: 31600 },
        costMultiplier: 1.15,
        production: 44,
        outputResource: "sarap",
        capacityPerUnit: 26500,
        consumes: null,
        unlock: { type: "building", id: "garden", count: 5 },
    },
    winery: {
        name: "Şaraphane",
        type: "bonus",
        baseCost: { karma: 252800, baharat: 76000, sarap: 38000 },
        costMultiplier: 1.24,
        targetResource: "sarap",
        bonusPerLevel: 0.15,
        unlock: { type: "building", id: "vineyard", count: 1 },
    },
    silkWorkshop: {
        name: "İpek Atölyesi",
        type: "producer",
        baseCost: { karma: 235000, sarap: 94000 },
        costMultiplier: 1.15,
        production: 79,
        outputResource: "ipek",
        capacityPerUnit: 47500,
        consumes: null,
        unlock: { type: "building", id: "vineyard", count: 5 },
    },
    loom: {
        name: "Dokuma Tezgahı",
        type: "bonus",
        baseCost: { karma: 752000, sarap: 225000, ipek: 113000 },
        costMultiplier: 1.24,
        targetResource: "ipek",
        bonusPerLevel: 0.15,
        unlock: { type: "building", id: "silkWorkshop", count: 1 },
    },
};
