export const BUILDINGS_DATA = {
    fountain: {
        name: "Güç Ocağı",
        type: "producer",
        baseCost: { power: 10 },
        costMultiplier: 1.15,
        production: 0.60,
        outputResource: "power",
        consumes: null,
        unlock: { type: "resource", id: "power", amount: 5 },
    },
    mansion: {
        name: "Kumandanlık",
        type: "bonus",
        baseCost: { power: 50 },
        costMultiplier: 1.75,
        targetResource: "power",
        bonusPerLevel: 0.02,
        unlock: { type: "building", id: "fountain", count: 5 },
    },
    depo: {
        name: "Depo",
        type: "storage",
        baseCost: { power: 500, su: 20 },
        costMultiplier: 1.15,
        unlock: { type: "building", id: "well", count: 1 },
    },
    ambar: {
        name: "Ambar",
        type: "capacityBonus",
        baseCost: { power: 1500, su: 80, yiyecek: 40 },
        costMultiplier: 1.15,
        capacityBonusPerLevel: 0.05,
        unlock: { type: "building", id: "farm", count: 1 },
    },
    well: {
        name: "Kuyu",
        type: "producer",
        baseCost: { power: 100 },
        costMultiplier: 1.15,
        production: 0.30,
        outputResource: "su",
        consumes: null,
        unlock: { type: "building", id: "fountain", count: 10 },
    },
    aqueduct: {
        name: "Çeşme",
        type: "bonus",
        baseCost: { power: 250, su: 30 },
        costMultiplier: 1.75,
        targetResource: "su",
        bonusPerLevel: 0.02,
        unlock: { type: "building", id: "well", count: 5 },
    },
    farm: {
        name: "Tarla",
        type: "producer",
        baseCost: { power: 300, su: 20 },
        costMultiplier: 1.15,
        production: 0.15,
        outputResource: "yiyecek",
        consumes: null,
        unlock: { type: "building", id: "well", count: 10 },
    },
    mill: {
        name: "Değirmen",
        type: "bonus",
        baseCost: { power: 600, su: 40, yiyecek: 20 },
        costMultiplier: 1.75,
        targetResource: "yiyecek",
        bonusPerLevel: 0.02,
        unlock: { type: "building", id: "farm", count: 5 },
    },
    lumberjack: {
        name: "Oduncu",
        type: "producer",
        baseCost: { power: 400, yiyecek: 50 },
        costMultiplier: 1.15,
        production: 0.08,
        outputResource: "odun",
        consumes: null,
        unlock: { type: "building", id: "farm", count: 10 },
    },
    lumbermill: {
        name: "Keresteci",
        type: "bonus",
        baseCost: { power: 1500, yiyecek: 80, odun: 30 },
        costMultiplier: 1.75,
        targetResource: "odun",
        bonusPerLevel: 0.02,
        unlock: { type: "building", id: "lumberjack", count: 1 },
    },
    tasOcagi: {
        name: "Taş Ocağı",
        type: "producer",
        baseCost: { power: 600, odun: 40 },
        costMultiplier: 1.15,
        production: 0.04,
        outputResource: "tas",
        consumes: null,
        unlock: { type: "building", id: "lumbermill", count: 1 },
    },
    tasAtolyesi: {
        name: "Taş Atölyesi",
        type: "bonus",
        baseCost: { power: 2500, odun: 80, tas: 15 },
        costMultiplier: 1.75,
        targetResource: "tas",
        bonusPerLevel: 0.02,
        unlock: { type: "building", id: "tasOcagi", count: 1 },
    },
    mine: {
        name: "Maden",
        type: "producer",
        baseCost: { power: 1200, odun: 80, tas: 20 },
        costMultiplier: 1.15,
        production: 0.02,
        outputResource: "maden",
        consumes: null,
        unlock: { type: "building", id: "lumberjack", count: 8 },
    },
    smeltery: {
        name: "Eritme Ocağı",
        type: "costBonus",
        baseCost: { power: 6000, odun: 250, maden: 60, tas: 30 },
        costMultiplier: 1.15,
        costDiscountPerLevel: 0.02,
        unlock: { type: "building", id: "mine", count: 5 },
    },
    academy: {
        name: "Akademi",
        type: "producer",
        baseCost: { power: 2500, maden: 120, tas: 50 },
        costMultiplier: 1.15,
        production: 0.04,
        outputResource: "bilgi",
        consumes: null,
        unlock: { type: "building", id: "mine", count: 8 },
    },
    library: {
        name: "Kütüphane",
        type: "workerBonus",
        baseCost: { power: 20000, maden: 400, bilgi: 100, tas: 60 },
        costMultiplier: 1.15,
        workerBonusPerLevel: 0.1,
        unlock: { type: "building", id: "academy", count: 5 },
    },
    temple: {
        name: "Tapınak",
        type: "producer",
        baseCost: { power: 5000, bilgi: 200, tas: 100 },
        costMultiplier: 1.15,
        production: 0.02,
        outputResource: "inanc",
        consumes: null,
        unlock: { type: "building", id: "academy", count: 10 },
    },
    altar: {
        name: "Sunak",
        type: "bonus",
        baseCost: { power: 35000, bilgi: 1200, inanc: 250, tas: 100 },
        costMultiplier: 1.75,
        targetResource: "inanc",
        bonusPerLevel: 0.02,
        happinessPerLevel: 1,
        unlock: { type: "building", id: "temple", count: 5 },
    },
    garden: {
        name: "Bahçe",
        type: "producer",
        baseCost: { power: 10000, inanc: 300, tas: 50 },
        costMultiplier: 1.15,
        production: 0.01,
        outputResource: "baharat",
        happinessPerLevel: 1,
        unlock: { type: "building", id: "temple", count: 10 },
    },
    spiceMill: {
        name: "Baharat Değirmeni",
        type: "bonus",
        baseCost: { power: 90000, inanc: 900, baharat: 5, tas: 100 },
        costMultiplier: 1.75,
        targetResource: "baharat",
        bonusPerLevel: 0.02,
        unlock: { type: "building", id: "garden", count: 5 },
    },
    vineyard: {
        name: "Üzüm Bağı",
        type: "producer",
        baseCost: { power: 20000, maden: 100, odun: 200 },
        costMultiplier: 1.15,
        production: 0.01,
        outputResource: "sarap",
        consumes: null,
        unlock: { type: "building", id: "garden", count: 8 },
    },
    winery: {
        name: "Şaraphane",
        type: "storageBonus",
        baseCost: { power: 200000, maden: 150, sarap: 4, tas: 150 },
        costMultiplier: 1.15,
        storageBonusPerLevel: 0.05,
        unlock: { type: "building", id: "vineyard", count: 1 },
    },
    silkWorkshop: {
        name: "İpek Atölyesi",
        type: "producer",
        baseCost: { power: 40000, su: 200, odun: 150 },
        costMultiplier: 1.15,
        production: 0.01,
        outputResource: "ipek",
        consumes: null,
        unlock: { type: "building", id: "vineyard", count: 8 },
    },
    loom: {
        name: "Dokuma Tezgahı",
        type: "costBonus",
        baseCost: { power: 250000, odun: 400, ipek: 2, tas: 200 },
        costMultiplier: 1.15,
        costDiscountPerLevel: 0.02,
        unlock: { type: "building", id: "silkWorkshop", count: 1 },
    },
    baraka: {
        name: "Baraka",
        type: "housing",
        baseCost: { power: 100, su: 20 },
        costMultiplier: 2.5,
        housingCapacity: 1,
        unlock: { type: "building", id: "fountain", count: 5 },
    },
    ev: {
        name: "Ev",
        type: "housing",
        baseCost: { power: 800, yiyecek: 40, odun: 20, tas: 15 },
        costMultiplier: 2.5,
        housingCapacity: 2,
        unlock: { type: "building", id: "baraka", count: 10 },
    },
};
