export const BUILDINGS_DATA = {
    fountain: {
        name: "Güç Ocağı",
        type: "producer",
        baseCost: { power: 10 },
        costMultiplier: 1.12,
        production: 0.625,
        outputResource: "power",
        consumes: null,
        unlock: { type: "resource", id: "power", amount: 10 },
    },
    mansion: {
        name: "Kumandanlık",
        type: "bonus",
        baseCost: { power: 75 },
        costMultiplier: 1.12,
        targetResource: "power",
        bonusPerLevel: 0.02,
        unlock: { type: "building", id: "fountain", count: 5 },
    },
    depo: {
        name: "Depo",
        type: "storage",
        baseCost: { power: 50 },
        costMultiplier: 1.75,
        unlock: { type: "building", id: "well", count: 1 },
    },
    ambar: {
        name: "Ambar",
        type: "capacityBonus",
        baseCost: { power: 150, su: 40, yiyecek: 20 },
        costMultiplier: 1.15,
        capacityBonusPerLevel: 0.05,
        unlock: { type: "building", id: "farm", count: 5 },
    },
    well: {
        name: "Kuyu",
        type: "producer",
        baseCost: { power: 100 },
        costMultiplier: 1.15,
        production: 0.30,
        outputResource: "su",
        consumes: null,
        unlock: { type: "building", id: "fountain", count: 5 },
    },
    aqueduct: {
        name: "Çeşme",
        type: "bonus",
        baseCost: { power: 250, su: 30 },
        costMultiplier: 1.12,
        targetResource: "su",
        bonusPerLevel: 0.02,
        unlock: { type: "building", id: "well", count: 5 },
    },
    farm: {
        name: "Tarla",
        type: "producer",
        baseCost: { power: 150, su: 20 },
        costMultiplier: 1.15,
        production: 0.15,
        outputResource: "yiyecek",
        consumes: null,
        unlock: { type: "building", id: "well", count: 5 },
    },
    mill: {
        name: "Değirmen",
        type: "bonus",
        baseCost: { power: 400, su: 30, yiyecek: 10 },
        costMultiplier: 1.15,
        targetResource: "yiyecek",
        bonusPerLevel: 0.02,
        unlock: { type: "building", id: "farm", count: 5 },
    },
    lumberjack: {
        name: "Oduncu",
        type: "producer",
        baseCost: { power: 200, yiyecek: 30 },
        costMultiplier: 1.15,
        production: 0.08,
        outputResource: "odun",
        consumes: null,
        unlock: { type: "building", id: "farm", count: 5 },
    },
    lumbermill: {
        name: "Keresteci",
        type: "bonus",
        baseCost: { power: 400, yiyecek: 30, odun: 10 },
        costMultiplier: 1.15,
        targetResource: "odun",
        bonusPerLevel: 0.02,
        unlock: { type: "building", id: "lumberjack", count: 1 },
    },
    tasOcagi: {
        name: "Taş Ocağı",
        type: "producer",
        baseCost: { power: 300, odun: 20 },
        costMultiplier: 1.15,
        production: 0.04,
        outputResource: "tas",
        consumes: null,
        unlock: { type: "building", id: "lumberjack", count: 1 },
    },
    tasAtolyesi: {
        name: "Taş Atölyesi",
        type: "bonus",
        baseCost: { power: 800, odun: 40, tas: 10 },
        costMultiplier: 1.15,
        targetResource: "tas",
        bonusPerLevel: 0.02,
        unlock: { type: "building", id: "tasOcagi", count: 1 },
    },
    mine: {
        name: "Maden",
        type: "producer",
        baseCost: { power: 600, odun: 40, tas: 10 },
        costMultiplier: 1.15,
        production: 0.02,
        outputResource: "maden",
        consumes: null,
        unlock: { type: "building", id: "lumberjack", count: 5 },
    },
    madenciKampi: {
        name: "Madenci Kampı",
        type: "bonus",
        baseCost: { power: 2000, maden: 25, tas: 15 },
        costMultiplier: 1.15,
        targetResource: "maden",
        bonusPerLevel: 0.02,
        unlock: { type: "building", id: "mine", count: 3 },
    },
    academy: {
        name: "Akademi",
        type: "producer",
        baseCost: { power: 1000, maden: 50, tas: 25 },
        costMultiplier: 1.15,
        production: 0.04,
        outputResource: "bilgi",
        consumes: null,
        unlock: { type: "building", id: "mine", count: 3 },
    },
    library: {
        name: "Kütüphane",
        type: "workerBonus",
        baseCost: { power: 4000, maden: 120, bilgi: 40, tas: 20, demir: 3 },
        costMultiplier: 1.15,
        workerBonusPerLevel: 0.1,
        unlock: { type: "building", id: "academy", count: 3 },
    },
    temple: {
        name: "Tapınak",
        type: "producer",
        baseCost: { power: 2000, bilgi: 80, tas: 40, demir: 2 },
        costMultiplier: 1.15,
        production: 0.02,
        outputResource: "inanc",
        consumes: null,
        unlock: { type: "building", id: "academy", count: 5 },
    },
    altar: {
        name: "Sunak",
        type: "bonus",
        baseCost: { power: 8000, bilgi: 400, inanc: 100, tas: 50 },
        costMultiplier: 1.15,
        targetResource: "inanc",
        bonusPerLevel: 0.02,
        happinessPerLevel: 1,
        unlock: { type: "building", id: "temple", count: 5 },
    },
    garden: {
        name: "Bahçe",
        type: "producer",
        baseCost: { power: 5000, inanc: 150, tas: 25 },
        costMultiplier: 1.15,
        production: 0.01,
        outputResource: "baharat",
        happinessPerLevel: 1,
        unlock: { type: "building", id: "temple", count: 5 },
    },
    spiceMill: {
        name: "Baharat Değirmeni",
        type: "bonus",
        baseCost: { power: 20000, inanc: 400, baharat: 3, tas: 50 },
        costMultiplier: 1.15,
        targetResource: "baharat",
        bonusPerLevel: 0.02,
        unlock: { type: "building", id: "garden", count: 5 },
    },
    vineyard: {
        name: "Üzüm Bağı",
        type: "producer",
        baseCost: { power: 10000, maden: 80, odun: 100 },
        costMultiplier: 1.15,
        production: 0.01,
        outputResource: "sarap",
        consumes: null,
        unlock: { type: "building", id: "garden", count: 3 },
    },
    winery: {
        name: "Şaraphane",
        type: "storageBonus",
        baseCost: { power: 40000, maden: 100, sarap: 3, tas: 75 },
        costMultiplier: 1.15,
        storageBonusPerLevel: 0.05,
        unlock: { type: "building", id: "vineyard", count: 1 },
    },
    silkWorkshop: {
        name: "İpek Atölyesi",
        type: "producer",
        baseCost: { power: 20000, su: 150, odun: 80 },
        costMultiplier: 1.15,
        production: 0.01,
        outputResource: "ipek",
        consumes: null,
        unlock: { type: "building", id: "vineyard", count: 3 },
    },
    loom: {
        name: "Dokuma Tezgahı",
        type: "costBonus",
        baseCost: { power: 60000, odun: 200, ipek: 2, tas: 100 },
        costMultiplier: 1.15,
        costDiscountPerLevel: 0.02,
        unlock: { type: "building", id: "silkWorkshop", count: 1 },
    },
    baraka: {
        name: "Baraka",
        type: "housing",
        baseCost: { power: 50, su: 10 },
        costMultiplier: 2.5,
        housingCapacity: 1,
        unlock: { type: "building", id: "fountain", count: 5 },
    },
    ev: {
        name: "Ev",
        type: "housing",
        baseCost: { power: 400, yiyecek: 20, odun: 10, tas: 5, kereste: 2 },
        costMultiplier: 1.15,
        housingCapacity: 2,
        unlock: { type: "building", id: "baraka", count: 5 },
    },
    workshop: {
        name: "Craft Atölyesi",
        type: "productBonus",
        baseCost: { power: 15000, odun: 300, maden: 100 },
        costMultiplier: 1.15,
        productBonusPerLevel: 0.06,
        unlock: {
            type: "all",
            conditions: [
                { type: "industry", id: "blacksmith" },
                { type: "pack", id: "autoClick", level: 1 },
            ],
        },
    },
    amphitheatre: {
        name: "Amfitiyatro",
        type: "producer",
        baseCost: { power: 30000, inanc: 200, tas: 75 },
        costMultiplier: 1.15,
        production: 0.01,
        outputResource: "kultur",
        consumes: null,
        unlock: { type: "building", id: "temple", count: 5 },
    },
    tradePost: {
        name: "Ticaret Merkezi",
        type: "tradeBonus",
        baseCost: { power: 50000, sarap: 5, ipek: 2, tas: 100 },
        costMultiplier: 1.15,
        tradeBonusPerLevel: 0.5,
        unlock: { type: "building", id: "vineyard", count: 3 },
    },
};
