export const INDUSTRY_DATA = {
    firin: {
        name: "Fırın",
        emoji: "🍞",
        description: "Fırında ekmek üretilir.",
        baseCost: { power: 425, su: 17, yiyecek: 42, tas: 13 },
        input: { yiyecek: 0.08, su: 0.02 },
        output: { ekmek: 0.06 },
        maxWorkers: 3,
        unlock: { type: "building", id: "farm", count: 5 },
    },
    keresteAtolyesi: {
        name: "Kereste Atölyesi",
        emoji: "🪚",
        description: "Odun keresteye işlenir.",
        baseCost: { power: 680, yiyecek: 68, odun: 25, tas: 13 },
        input: { odun: 0.06 },
        output: { kereste: 0.01 },
        maxWorkers: 3,
        unlock: { type: "building", id: "lumberjack", count: 5 },
    },
    blacksmith: {
        name: "Demirci",
        emoji: "⚒️",
        description: "Maden demire işlenir.",
        baseCost: { power: 1700, odun: 128, maden: 42 },
        input: { maden: 0.08 },
        output: { demir: 0.01 },
        maxWorkers: 3,
        unlock: { type: "building", id: "mine", count: 3 },
    },
    sifaOcagi: {
        name: "Şifa Ocağı",
        emoji: "⚕️",
        description: "Şifalı ilaçlar üretilir.",
        baseCost: { power: 6800, bilgi: 425, inanc: 128 },
        input: { inanc: 0.02, baharat: 0.01 },
        output: { ilac: 0.01 },
        maxWorkers: 3,
        unlock: { type: "building", id: "garden", count: 1 },
    },
    damitimevi: {
        name: "Damıtımevi",
        emoji: "🥃",
        description: "Şaraptan konyak üretilir.",
        baseCost: { power: 12750, inanc: 340, baharat: 68 },
        input: { sarap: 0.02 },
        output: { konyak: 0.005 },
        maxWorkers: 3,
        unlock: { type: "building", id: "vineyard", count: 3 },
    },
    kumasAtolyesi: {
        name: "Kumaş Atölyesi",
        emoji: "🧶",
        description: "İpek kumaşa işlenir.",
        baseCost: { power: 25500, baharat: 128, sarap: 68 },
        input: { ipek: 0.01 },
        output: { kumas: 0.005 },
        maxWorkers: 3,
        unlock: { type: "building", id: "silkWorkshop", count: 3 },
    },
    celikFirini: {
        name: "Çelik Fırını",
        emoji: "🔥",
        description: "Demir ve maden çeliğe işlenir.",
        baseCost: { power: 51000, maden: 638, odun: 340 },
        input: { demir: 0.02, maden: 0.02 },
        output: { celik: 0.005 },
        maxWorkers: 4,
        unlock: {
            type: "all",
            conditions: [
                { type: "industry", id: "blacksmith" },
                { type: "pack", id: "metalIsleme", level: 1 },
            ],
        },
    },
    mermerAtolyesi: {
        name: "Mermer Atölyesi",
        emoji: "🗿",
        description: "Taş mermere işlenir.",
        baseCost: { power: 68000, tas: 850, odun: 255 },
        input: { tas: 0.05 },
        output: { mermer: 0.01 },
        maxWorkers: 3,
        unlock: { type: "building", id: "temple", count: 5 },
    },
    mobilyaAtolyesi: {
        name: "Mobilya Atölyesi",
        emoji: "🛋️",
        description: "Kereste ve çelik mobilyaya işlenir.",
        baseCost: { power: 85000, odun: 340, maden: 425, celik: 1 },
        input: { kereste: 0.01, celik: 0.01 },
        output: { mobilya: 0.005 },
        maxWorkers: 3,
        unlock: { type: "industry", id: "celikFirini" },
    },
    mucevherAtolyesi: {
        name: "Mücevher Atölyesi",
        emoji: "💍",
        description: "Kumaş, çelik ve mermer mücevhere işlenir.",
        baseCost: { power: 102000, baharat: 213, kumas: 13, mermer: 7 },
        input: { kumas: 0.02, celik: 0.01, mermer: 0.01 },
        output: { mucevher: 0.01 },
        maxWorkers: 3,
        unlock: { type: "industry", id: "kumasAtolyesi" },
    },
    heykelAtolyesi: {
        name: "Heykel Atölyesi",
        emoji: "🏛️",
        description: "Mermer ve çelikten heykel işlenir.",
        baseCost: { power: 127500, mermer: 21, celik: 10, tas: 425 },
        input: { mermer: 0.02, celik: 0.01 },
        output: { heykel: 0.005 },
        maxWorkers: 3,
        unlock: { type: "industry", id: "mermerAtolyesi" },
    },
    darphane: {
        name: "Darphane",
        emoji: "🪙",
        description: "Şarap ve ipekten altın basılır.",
        baseCost: { power: 51000, sarap: 17, ipek: 7 },
        input: { sarap: 0.02, ipek: 0.01 },
        output: { altin: 0.01 },
        maxWorkers: 3,
        unlock: {
            type: "all",
            conditions: [
                { type: "industry", id: "kumasAtolyesi" },
                { type: "pack", id: "yazi", level: 1 },
            ],
        },
    },
};
