export const INDUSTRY_DATA = {
    firin: {
        name: "Fırın",
        emoji: "🍞",
        description: "Fırında ekmek üretilir.",
        baseCost: { power: 500, su: 20, yiyecek: 50, tas: 15 },
        input: { yiyecek: 0.08, su: 0.02 },
        output: { ekmek: 0.06 },
        maxWorkers: 3,
        unlock: { type: "building", id: "farm", count: 5 },
        tier: "processed",
    },
    keresteAtolyesi: {
        name: "Kereste Atölyesi",
        emoji: "🪚",
        description: "Odun keresteye işlenir.",
        baseCost: { power: 800, yiyecek: 80, odun: 30, tas: 15 },
        input: { odun: 0.06 },
        output: { kereste: 0.01 },
        maxWorkers: 3,
        unlock: { type: "building", id: "lumberjack", count: 5 },
        tier: "processed",
    },
    blacksmith: {
        name: "Demirci",
        emoji: "⚒️",
        description: "Maden demire işlenir.",
        baseCost: { power: 2000, odun: 150, maden: 50 },
        input: { maden: 0.08 },
        output: { demir: 0.01 },
        maxWorkers: 3,
        unlock: { type: "building", id: "mine", count: 3 },
        tier: "processed",
    },
    sifaOcagi: {
        name: "Şifa Ocağı",
        emoji: "⚕️",
        description: "Şifalı ilaçlar üretilir.",
        baseCost: { power: 8000, bilgi: 500, inanc: 150 },
        input: { inanc: 0.02, baharat: 0.01 },
        output: { ilac: 0.01 },
        maxWorkers: 3,
        unlock: { type: "building", id: "garden", count: 1 },
        tier: "craft",
    },
    damitimevi: {
        name: "Damıtımevi",
        emoji: "🥃",
        description: "Şaraptan konyak üretilir.",
        baseCost: { power: 15000, inanc: 400, baharat: 80 },
        input: { sarap: 0.02 },
        output: { konyak: 0.005 },
        maxWorkers: 3,
        unlock: { type: "building", id: "vineyard", count: 3 },
        tier: "processed",
    },
    kumasAtolyesi: {
        name: "Kumaş Atölyesi",
        emoji: "🧶",
        description: "İpek kumaşa işlenir.",
        baseCost: { power: 30000, baharat: 150, sarap: 80 },
        input: { ipek: 0.01 },
        output: { kumas: 0.005 },
        maxWorkers: 3,
        unlock: { type: "building", id: "silkWorkshop", count: 3 },
        tier: "processed",
    },
    celikFirini: {
        name: "Çelik Fırını",
        emoji: "🔥",
        description: "Demir ve maden çeliğe işlenir.",
        baseCost: { power: 60000, maden: 750, odun: 400 },
        input: { demir: 0.02, maden: 0.02 },
        output: { celik: 0.005 },
        maxWorkers: 4,
        unlock: {
            type: "all",
            conditions: [
                { type: "industry", id: "blacksmith" },
                { type: "pack", id: "metalIsleme", level: 1 },
            ],
        },
        tier: "craft",
    },
    mermerAtolyesi: {
        name: "Mermer Atölyesi",
        emoji: "🗿",
        description: "Taş mermere işlenir.",
        baseCost: { power: 80000, tas: 1000, odun: 300 },
        input: { tas: 0.05 },
        output: { mermer: 0.01 },
        maxWorkers: 3,
        unlock: { type: "building", id: "temple", count: 5 },
        tier: "processed",
    },
    mobilyaAtolyesi: {
        name: "Mobilya Atölyesi",
        emoji: "🛋️",
        description: "Kereste ve çelik mobilyaya işlenir.",
        baseCost: { power: 100000, odun: 400, maden: 500, celik: 1 },
        input: { kereste: 0.01, celik: 0.01 },
        output: { mobilya: 0.005 },
        maxWorkers: 3,
        unlock: { type: "industry", id: "celikFirini" },
        tier: "craft",
    },
    mucevherAtolyesi: {
        name: "Mücevher Atölyesi",
        emoji: "💍",
        description: "Kumaş, çelik ve mermer mücevhere işlenir.",
        baseCost: { power: 120000, baharat: 250, kumas: 15, mermer: 8 },
        input: { kumas: 0.02, celik: 0.01, mermer: 0.01 },
        output: { mucevher: 0.01 },
        maxWorkers: 3,
        unlock: { type: "industry", id: "kumasAtolyesi" },
        tier: "craft",
    },
    heykelAtolyesi: {
        name: "Heykel Atölyesi",
        emoji: "🏛️",
        description: "Mermer ve çelikten heykel işlenir.",
        baseCost: { power: 150000, mermer: 25, celik: 12, tas: 500 },
        input: { mermer: 0.02, celik: 0.01 },
        output: { heykel: 0.005 },
        maxWorkers: 3,
        unlock: { type: "industry", id: "mermerAtolyesi" },
        tier: "craft",
    },
    darphane: {
        name: "Darphane",
        emoji: "🪙",
        description: "Şarap ve ipekten altın basılır.",
        baseCost: { power: 60000, sarap: 20, ipek: 8 },
        input: { sarap: 0.02, ipek: 0.01 },
        output: { altin: 0.01 },
        maxWorkers: 3,
        unlock: {
            type: "all",
            conditions: [
                { type: "industry", id: "kumasAtolyesi" },
                { type: "pack", id: "yazi", level: 1 },
            ],
        },
        tier: "currency",
    },
};
