/* ═══════════════════════════════════════════════════════════════════════════ */
/*                          SANAYİ VERİLERİ                                   */
/* ═══════════════════════════════════════════════════════════════════════════ */

export const INDUSTRY_DATA = {
    firin: {
        name: "Fırın",
        emoji: "🍞",
        description: "Fırında ekmek üretilir.",
        baseCost: { power: 425, su: 17, yiyecek: 42 },
        input: { yiyecek: 0.080, su: 0.020 },
        output: { ekmek: 0.060 },
        maxWorkers: 3,
        unlock: { type: "building", id: "farm", count: 5 },
    },
    blacksmith: {
        name: "Demirci",
        emoji: "⚒️",
        description: "Maden demire işlenir.",
        baseCost: { power: 1700, yiyecek: 100, tas: 30 },
        input: { maden: 0.080 },
        output: { demir: 0.010 },
        maxWorkers: 3,
        unlock: { type: "building", id: "mine", count: 3 },
    },
    celikFirini: {
        name: "Çelik Fırını",
        emoji: "🔥",
        description: "Maden ve demir çeliğe işlenir.",
        baseCost: { power: 51000, tas: 638, yiyecek: 340 },
        input: { maden: 0.020, demir: 0.020 },
        output: { celik: 0.005 },
        maxWorkers: 4,
        unlock: {
            type: "all",
            conditions: [
                { type: "industry", id: "blacksmith" },
                { type: "pack", id: "metalIsleme", level: 1 },
            ],
        },
    },
    mermerAtolyesi: {
        name: "Mermer Atölyesi",
        emoji: "🗿",
        description: "Taş mermere işlenir.",
        baseCost: { power: 68000, tas: 850, yiyecek: 255 },
        input: { tas: 0.050 },
        output: { mermer: 0.010 },
        maxWorkers: 3,
        unlock: { type: "building", id: "temple", count: 5 },
    },
    kumasAtolyesi: {
        name: "Kumaş Atölyesi",
        emoji: "🧶",
        description: "İpek kumaşa işlenir.",
        baseCost: { power: 25500, su: 128, yiyecek: 68 },
        input: { ipek: 0.010 },
        output: { kumas: 0.005 },
        maxWorkers: 3,
        unlock: { type: "building", id: "silkWorkshop", count: 3 },
    },
    sifaOcagi: {
        name: "Şifa Ocağı",
        emoji: "⚕️",
        description: "İnanç ve bilgiden ilaç üretilir.",
        baseCost: { power: 6800, bilgi: 180, inanc: 128 },
        input: { inanc: 0.020, bilgi: 0.010 },
        output: { ilac: 0.010 },
        maxWorkers: 3,
        unlock: { type: "building", id: "temple", count: 1 },
    },
    mobilyaAtolyesi: {
        name: "Mobilya Atölyesi",
        emoji: "🛋️",
        description: "Taş ve çelikten mobilya üretilir.",
        baseCost: { power: 85000, yiyecek: 340, maden: 425 },
        input: { tas: 0.010, celik: 0.010 },
        output: { mobilya: 0.005 },
        maxWorkers: 3,
        unlock: { type: "industry", id: "celikFirini" },
    },
    heykelAtolyesi: {
        name: "Heykel Atölyesi",
        emoji: "🏛️",
        description: "Mermer ve çelikten heykel üretilir.",
        baseCost: { power: 127500, tas: 21, yiyecek: 10 },
        input: { mermer: 0.020, celik: 0.010 },
        output: { heykel: 0.005 },
        maxWorkers: 3,
        unlock: { type: "industry", id: "mermerAtolyesi" },
    },
    mucevherAtolyesi: {
        name: "Mücevher Atölyesi",
        emoji: "💍",
        description: "Kumaş, çelik ve mermerden mücevher üretilir.",
        baseCost: { power: 102000, su: 213, yiyecek: 13 },
        input: { kumas: 0.020, celik: 0.010, mermer: 0.010 },
        output: { mucevher: 0.002 },
        maxWorkers: 3,
        unlock: { type: "industry", id: "kumasAtolyesi" },
    },
    darphane: {
        name: "Darphane",
        emoji: "🪙",
        description: "Bilgi ve ipekten altın basılır.",
        baseCost: { power: 51000, bilgi: 17, yiyecek: 7 },
        input: { bilgi: 0.010, ipek: 0.005 },
        output: { altin: 0.015 },
        maxWorkers: 3,
        unlock: {
            type: "all",
            conditions: [
                { type: "industry", id: "kumasAtolyesi" },
                { type: "pack", id: "yazi", level: 1 },
            ],
        },
    },
};
