/* ═══════════════════════════════════════════════════════════════════════════ */
/*                          PAKET VERİLERİ                                   */
/* ═══════════════════════════════════════════════════════════════════════════ */

export const PACKS_DATA = {
    clickPower: {
        name: "Başlangıç Paketi",
        emoji: "🛠️",
        description: "Tüm binaların üretimini %5 artırır",
        baseCost: { bilgi: 30 },
        costMultiplier: 1.20,
        productionBonusPerLevel: 0.05,
    },
    critClick: {
        name: "Çiftlik Paketi",
        emoji: "💥",
        description: "Güç üretimini %8 artırır",
        baseCost: { bilgi: 70 },
        costMultiplier: 1.20,
        powerBonusPerLevel: 0.08,
        unlock: { type: "pack", id: "clickPower", level: 1 },
    },
    autoClick: {
        name: "Madenci Paketi",
        emoji: "🔧",
        description: "İşlenmiş ve craft ürün üretimini %6 artırır",
        baseCost: { bilgi: 160 },
        costMultiplier: 1.20,
        productBonusPerLevel: 0.06,
        unlock: { type: "pack", id: "critClick", level: 1 },
    },
    powerPatronage: {
        name: "Bilge Paketi",
        emoji: "⚔️",
        description: "Güç üretimini %10 artırır",
        baseCost: { bilgi: 380 },
        costMultiplier: 1.20,
        powerBonusPerLevel: 0.10,
        unlock: { type: "pack", id: "autoClick", level: 1 },
    },
    metalIsleme: {
        name: "Savaşçı Paketi",
        emoji: "⚙️",
        description: "İşlenmiş ve craft ürün üretimini %8 artırır",
        baseCost: { bilgi: 850 },
        costMultiplier: 1.20,
        productBonusPerLevel: 0.08,
        unlock: { type: "pack", id: "powerPatronage", level: 1 },
    },
    eritme: {
        name: "Ticaret Paketi",
        emoji: "🔨",
        description: "Tüm bina maliyetlerini %2 azaltır",
        baseCost: { bilgi: 1200 },
        costMultiplier: 1.20,
        costDiscountPerLevel: 0.02,
        unlock: { type: "pack", id: "metalIsleme", level: 1 },
    },
    yazi: {
        name: "İnanç Paketi",
        emoji: "📖",
        description: "Tüm binaların üretimini %5 artırır",
        baseCost: { bilgi: 2800 },
        costMultiplier: 1.20,
        productionBonusPerLevel: 0.05,
        unlock: { type: "pack", id: "metalIsleme", level: 1 },
    },
    isciBilimi: {
        name: "İpek Yolu Paketi",
        emoji: "👷",
        description: "Sanayi işçilerinin üretimini %10 artırır",
        baseCost: { bilgi: 240 },
        costMultiplier: 1.20,
        workerBonusPerLevel: 0.10,
        unlock: { type: "building", id: "academy", count: 3 },
    },
    depoBilimi: {
        name: "İmparatorluk",
        emoji: "🏗️",
        description: "Tüm kaynak depo kapasitelerini %5 artırır",
        baseCost: { bilgi: 500 },
        costMultiplier: 1.20,
        storageBonusPerLevel: 0.05,
        unlock: { type: "building", id: "academy", count: 3 },
    },
    maliyetBilimi: {
        name: "Efsane Paketi",
        emoji: "📐",
        description: "Tüm bina maliyetlerini %2 azaltır",
        baseCost: { bilgi: 800 },
        costMultiplier: 1.20,
        costDiscountPerLevel: 0.02,
        unlock: { type: "building", id: "silkWorkshop", count: 1 },
    },
    craftAtolyesi: {
        name: "Kutsal Paket",
        emoji: "🔨",
        description: "İşlenmiş ve craft ürün üretimini %8 artırır",
        baseCost: { bilgi: 640 },
        costMultiplier: 1.20,
        productBonusPerLevel: 0.08,
        unlock: { type: "pack", id: "autoClick", level: 1 },
    },
    ticaretBilimi: {
        name: "Son Paket",
        emoji: "📈",
        description: "Tüccar sıklığını ve teklif boyutunu %50 artırır",
        baseCost: { bilgi: 500, ipek: 5 },
        costMultiplier: 1.20,
        tradeBonusPerLevel: 0.50,
        unlock: { type: "building", id: "theatre", count: 3 },
    },
};
