/* ═══════════════════════════════════════════════════════════════════════════ */
/*                          PAKET VERİLERİ                                   */
/* ═══════════════════════════════════════════════════════════════════════════ */

export const PACKS_DATA = {
    clickPower: {
        name: "Üretim Gücü",
        emoji: "🛠️",
        description: "Tüm binaların üretimini %5 artırır",
        baseCost: { bilgi: 30 },
        costMultiplier: 1.20,
        productionBonusPerLevel: 0.05,
    },
    critClick: {
        name: "Kudret",
        emoji: "⚡",
        description: "Güç üretimini %8 artırır",
        baseCost: { bilgi: 70 },
        costMultiplier: 1.20,
        powerBonusPerLevel: 0.08,
        unlock: { type: "pack", id: "clickPower", level: 1 },
    },
    autoClick: {
        name: "Zanaat",
        emoji: "🧰",
        description: "İşlenmiş ve craft ürün üretimini %8 artırır",
        baseCost: { bilgi: 160 },
        costMultiplier: 1.20,
        productBonusPerLevel: 0.08,
        unlock: { type: "pack", id: "critClick", level: 1 },
    },
    powerPatronage: {
        name: "İktidar",
        emoji: "👑",
        description: "Güç üretimini %10 artırır",
        baseCost: { bilgi: 380 },
        costMultiplier: 1.20,
        powerBonusPerLevel: 0.1,
        unlock: { type: "pack", id: "autoClick", level: 1 },
    },
    metalIsleme: {
        name: "Metal İşleme",
        emoji: "⚙️",
        description: "İşlenmiş ve craft ürün üretimini %8 artırır",
        baseCost: { bilgi: 850 },
        costMultiplier: 1.20,
        productBonusPerLevel: 0.08,
        unlock: { type: "pack", id: "powerPatronage", level: 1 },
    },
    eritme: {
        name: "Eritme",
        emoji: "⚒️",
        description: "Tüm bina maliyetlerini %2 azaltır",
        baseCost: { bilgi: 1900 },
        costMultiplier: 1.20,
        costDiscountPerLevel: 0.02,
        unlock: { type: "pack", id: "metalIsleme", level: 1 },
    },
    yazi: {
        name: "Yazı",
        emoji: "📜",
        description: "Tüm binaların üretimini %5 artırır",
        baseCost: { bilgi: 4200 },
        costMultiplier: 1.20,
        productionBonusPerLevel: 0.05,
        unlock: { type: "pack", id: "metalIsleme", level: 1 },
    },
    isciBilimi: {
        name: "İşçi Bilimi",
        emoji: "🧑‍🏭",
        description: "Sanayi işçilerinin üretimini %10 artırır",
        baseCost: { bilgi: 240 },
        costMultiplier: 1.20,
        workerBonusPerLevel: 0.1,
        unlock: { type: "building", id: "academy", count: 3 },
    },
    depoBilimi: {
        name: "Depo Bilimi",
        emoji: "📦",
        description: "Tüm kaynak depo kapasitelerini %5 artırır",
        baseCost: { sarap: 20 },
        costMultiplier: 1.20,
        storageBonusPerLevel: 0.05,
        unlock: { type: "building", id: "vineyard", count: 1 },
    },
    maliyetBilimi: {
        name: "Maliyet Bilimi",
        emoji: "🏷️",
        description: "Tüm bina maliyetlerini %2 azaltır",
        baseCost: { ipek: 10 },
        costMultiplier: 1.20,
        costDiscountPerLevel: 0.02,
        unlock: { type: "building", id: "silkWorkshop", count: 1 },
    },
    craftAtolyesi: {
        name: "Craft Atölyesi",
        emoji: "🧵",
        description: "İşlenmiş ve craft ürün üretimini %6 artırır",
        baseCost: { bilgi: 640 },
        costMultiplier: 1.20,
        productBonusPerLevel: 0.06,
        unlock: { type: "pack", id: "autoClick", level: 1 },
    },
    ticaretBilimi: {
        name: "Ticaret Merkezi",
        emoji: "🛒",
        description: "Tüccar sıklığını ve teklif boyutunu %50 artırır",
        baseCost: { sarap: 40, ipek: 20 },
        costMultiplier: 1.20,
        tradeBonusPerLevel: 0.5,
        unlock: { type: "building", id: "vineyard", count: 3 },
    },
};
