export const PACKS_DATA = {
    clickPower: {
        name: "Üretim Gücü",
        emoji: "🛠️",
        description: "Tüm binaların üretimini %5 artırır",
        baseCost: { bilgi: 30 },
        costMultiplier: 1.17,
        productionBonusPerLevel: 0.05,
    },
    critClick: {
        name: "Kudret",
        emoji: "⚡",
        description: "Güç üretimini %8 artırır",
        baseCost: { bilgi: 100 },
        costMultiplier: 1.25,
        powerBonusPerLevel: 0.08,
        unlock: { type: "pack", id: "clickPower", level: 1 },
    },
    autoClick: {
        name: "Zanaat",
        emoji: "🧰",
        description: "İşlenmiş ve craft ürün üretimini %8 artırır",
        baseCost: { bilgi: 300 },
        costMultiplier: 1.22,
        productBonusPerLevel: 0.08,
        unlock: { type: "pack", id: "critClick", level: 1 },
    },
    powerPatronage: {
        name: "İktidar",
        emoji: "👑",
        description: "Güç üretimini %10 artırır",
        baseCost: { bilgi: 500 },
        costMultiplier: 1.17,
        powerBonusPerLevel: 0.1,
        unlock: { type: "pack", id: "autoClick", level: 1 },
    },
    metalIsleme: {
        name: "Metal İşleme",
        emoji: "⚙️",
        description: "İşlenmiş ve craft ürün üretimini %8 artırır",
        baseCost: { bilgi: 900 },
        costMultiplier: 1.22,
        productBonusPerLevel: 0.08,
        unlock: { type: "pack", id: "powerPatronage", level: 1 },
    },
    eritme: {
        name: "Eritme",
        emoji: "⚒️",
        description: "Tüm bina maliyetlerini %2 azaltır",
        baseCost: { bilgi: 1500 },
        costMultiplier: 1.17,
        costDiscountPerLevel: 0.02,
        unlock: { type: "pack", id: "metalIsleme", level: 1 },
    },
    yazi: {
        name: "Yazı",
        emoji: "📜",
        description: "Tüm binaların üretimini %5 artırır",
        baseCost: { bilgi: 3600 },
        costMultiplier: 1.17,
        productionBonusPerLevel: 0.05,
        unlock: { type: "pack", id: "metalIsleme", level: 1 },
    },
};
