/* ═══════════════════════════════════════════════════════════════════════════ */
/*                          KAYNAK TANIMLARI                                   */
/* ═══════════════════════════════════════════════════════════════════════════ */

export const RESOURCES = {
    power: {
        name: "Güç",
        emoji: "⚡",
        tier: 0,
        baseCapacity: Infinity,
        storagePerDepo: 0,
        storagePerAmbar: 0,
        colorBright: "#ffe08a",
        colorDark: "#a8862f",
    },
    su: {
        name: "Su",
        emoji: "💧",
        tier: 1,
        baseCapacity: 1000,
        storagePerDepo: 200,
        storagePerAmbar: 0,
        satisFiyati: [1, 2],
        colorBright: "#5bc9ff",
        colorDark: "#1f6fa8",
    },
    yiyecek: {
        name: "Yiyecek",
        emoji: "🌾",
        tier: 1,
        baseCapacity: 1250,
        storagePerDepo: 250,
        storagePerAmbar: 0,
        satisFiyati: [1, 3],
        colorBright: "#ffd68a",
        colorDark: "#b07d2c",
    },
    bilgi: {
        name: "Bilgi",
        emoji: "📜",
        tier: 2,
        baseCapacity: 500,
        storagePerDepo: 100,
        storagePerAmbar: 0,
        satisFiyati: [2, 4],
        colorBright: "#9cc9ff",
        colorDark: "#4e7ea8",
    },
    tas: {
        name: "Taş",
        emoji: "🪨",
        tier: 2,
        baseCapacity: 600,
        storagePerDepo: 120,
        storagePerAmbar: 0,
        satisFiyati: [1, 3],
        colorBright: "#b8b8a8",
        colorDark: "#6e6e5c",
    },
    maden: {
        name: "Mineral",
        emoji: "⛏️",
        tier: 2,
        baseCapacity: 400,
        storagePerDepo: 80,
        storagePerAmbar: 0,
        satisFiyati: [3, 5],
        colorBright: "#bcc7d1",
        colorDark: "#6f7c8c",
    },
    kultur: {
        name: "Kültür",
        emoji: "🎭",
        tier: 3,
        baseCapacity: 200,
        storagePerDepo: 40,
        storagePerAmbar: 0,
        satisFiyati: [5, 8],
        colorBright: "#f5d0a0",
        colorDark: "#a87840",
    },
    inanc: {
        name: "İnanç",
        emoji: "🕯️",
        tier: 3,
        baseCapacity: 150,
        storagePerDepo: 30,
        storagePerAmbar: 0,
        satisFiyati: [6, 10],
        colorBright: "#e0aaff",
        colorDark: "#8a45b8",
    },
    ipek: {
        name: "İpek",
        emoji: "🧵",
        tier: 3,
        baseCapacity: 100,
        storagePerDepo: 20,
        storagePerAmbar: 0,
        satisFiyati: [8, 15],
        colorBright: "#ffd9e8",
        colorDark: "#b06f93",
    },
    altin: {
        name: "Altın",
        emoji: "💰",
        tier: -1,
        baseCapacity: Infinity,
        storagePerDepo: 0,
        storagePerAmbar: 0,
        colorBright: "#ffe95c",
        colorDark: "#b8860b",
    },
    ekmek: {
        name: "Ekmek",
        emoji: "🍞",
        tier: "product",
        baseCapacity: 500,
        storagePerDepo: 100,
        storagePerAmbar: 0,
    },
    demir: {
        name: "Demir",
        emoji: "⚒️",
        tier: "product",
        baseCapacity: 300,
        storagePerDepo: 60,
        storagePerAmbar: 0,
    },
    celik: {
        name: "Çelik",
        emoji: "🔩",
        tier: "product",
        baseCapacity: 200,
        storagePerDepo: 40,
        storagePerAmbar: 0,
    },
    mermer: {
        name: "Mermer",
        emoji: "🗿",
        tier: "product",
        baseCapacity: 300,
        storagePerDepo: 60,
        storagePerAmbar: 0,
    },
    kumas: {
        name: "Kumaş",
        emoji: "🧶",
        tier: "product",
        baseCapacity: 200,
        storagePerDepo: 40,
        storagePerAmbar: 0,
    },
    ilac: {
        name: "İlaç",
        emoji: "⚕️",
        tier: "product",
        baseCapacity: 300,
        storagePerDepo: 60,
        storagePerAmbar: 0,
    },
    mobilya: {
        name: "Mobilya",
        emoji: "🛋️",
        tier: "product",
        baseCapacity: 200,
        storagePerDepo: 40,
        storagePerAmbar: 0,
    },
    heykel: {
        name: "Heykel",
        emoji: "🏛️",
        tier: "product",
        baseCapacity: 200,
        storagePerDepo: 40,
        storagePerAmbar: 0,
    },
    mucevher: {
        name: "Mücevher",
        emoji: "💍",
        tier: "product",
        baseCapacity: 100,
        storagePerDepo: 20,
        storagePerAmbar: 0,
    },
};
