export const RESOURCES = {
    karma: {
        name: "Karma",
        emoji: "🔅",
        baseCapacity: Infinity,
        colorBright: "#ffe08a",
        colorDark: "#a8862f",
    },
    su: {
        name: "Su",
        emoji: "💧",
        baseCapacity: 50,
        colorBright: "#5bc9ff",
        colorDark: "#1f6fa8",
    },
    yiyecek: {
        name: "Yiyecek",
        emoji: "🌾",
        baseCapacity: 90,
        colorBright: "#ffd68a",
        colorDark: "#b07d2c",
    },
    odun: {
        name: "Odun",
        emoji: "🪵",
        baseCapacity: 160,
        colorBright: "#cd9b70",
        colorDark: "#7d4e2c",
    },
    maden: {
        name: "Mineral",
        emoji: "⛏️",
        baseCapacity: 280,
        colorBright: "#bcc7d1",
        colorDark: "#6f7c8c",
    },
    bilgi: {
        name: "Bilgi",
        emoji: "📖",
        baseCapacity: 500,
        colorBright: "#9cc9ff",
        colorDark: "#4e7ea8",
    },
    inanc: {
        name: "İnanç",
        emoji: "🕯️",
        baseCapacity: 900,
        colorBright: "#e0aaff",
        colorDark: "#8a45b8",
    },
    baharat: {
        name: "Baharat",
        emoji: "🌶️",
        baseCapacity: 1600,
        colorBright: "#ff9a7a",
        colorDark: "#b8472f",
    },
    sarap: {
        name: "Şarap",
        emoji: "🍷",
        baseCapacity: 2900,
        colorBright: "#ff8a9a",
        colorDark: "#a83f55",
    },
    ipek: {
        name: "İpek",
        emoji: "🧵",
        baseCapacity: 5200,
        colorBright: "#ffd9e8",
        colorDark: "#b06f93",
    },
};
